# Manifest for nginx deployment from https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizontal-pod-autoscaler-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.7.9
          ports:
            - containerPort: 80
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
