---
# https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
apiVersion: batch/v1
kind: Job
metadata:
  name: jobs-simple-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          image: perl:5.34.0
          name: jobs-simple-container
