apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: /usr/share/nginx/html
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: my-pvclaim