---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: external-lb
spec:
  # Controller refers to the name of the controller that should handle this class. This allows for different "flavors" that are controlled by the same controller. For example, you may have different Parameters for the same implementing controller. This should be specified as a domain-prefixed path no more than 250 characters in length, e.g. "acme.io/ingress-controller".  This field is immutable.
  controller: example.com/ingress-controller
  # Parameters is a link to a custom resource containing additional configuration for the controller. This is optional if the controller does not require extra parameters. IngressClassParametersReference identifies an API object. This can be used to specify a cluster or namespace-scoped resource.
  parameters:
    apiGroup: k8s.example.com
    kind: IngressParameters
    name: external-lb
